name: Deploy To Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependcies
        uses: actions/cache@v4
        env:
          cache-name: npm-${{ hashFiles('package-lock.json')}}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Install dependcies
        run: npm ci
      - name: Run prettier
        run: npm run prettier
      - name: Run eslint
        run: npm run lint
      - name: Run commitlint
        run: npx run commitlint --from=HEAD~1 --to=HEAD --verbose

  build:
    runs-on: ubuntu-latest
    container:
      image: node:22
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependcies
        uses: actions/cache@v4
        env:
          cache-name: npm-${{ hashFiles('package-lock.json')}}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      - name: Create env file
        run: |
          touch .env
          echo "VITE_FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}" > .env
      - name: Install dependcies
        run: npm ci --production
      - name: Build project
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
