name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: node:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 22.13.1
      - name: Install dependcies
        run: npm ci 
      - name: Run prettier
        run: npm run prettier
      - name: Run linter
        run: npm run lint
      - name: Run commitlint
        run: npx run commitlint --from=HEAD~1 --to=HEAD --verbose
      

  