name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependcies
        uses: actions/cache@v2
        env: 
          cache-name: npm-${{ hashFiles(package-lock.json)}} 
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-key: ${{ env.cache-name }}

      - name: Install dependcies
        run: npm ci 
      - name: Run prettier
        run: npm run prettier
      - name: Run linter
        run: npm run lint
      - name: Run commitlint
        run: npx run commitlint --from=HEAD~1 --to=HEAD --verbose
      

  